python youtube_api.py  --file="/Users/narda.ballesteros/Desktop/junio.mp4"
                       --title="Sport_video"
                       --description="home run"
                       --keywords="sport,homerun"
                       --category="17"
                       --privacyStatus="private"